sync with the audio-demo

diff --git a/.github/workflows/build_and_test.yml b/.github/workflows/build_and_test.yml
--- a/.github/workflows/build_and_test.yml
+++ b/.github/workflows/build_and_test.yml
@@ -13,12 +13,71 @@ on:
         description: "ref of the branch"
 
 jobs:
-  build-and-test-linux:
-    name: "Build and tests: ${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.build_type}}"
+
+  get-resources:
+    runs-on: ubuntu-latest
+    outputs:
+      number_of_jobs: ${{ steps.set-value.outputs.number_of_jobs }}
+    steps:
+      - name: Choose a number of concurrent jobs
+        id: number-of-jobs
+        shell: bash
+        run: |
+          # Our arm machines have more cores than memory (in gb). This choses a number of concurrent jobs equal to min(mem_in_gb, cpus)
+          VALUE=$(($(free -g | grep Mem: | awk '{print $2}') < $(nproc) ? $(free -g | grep Mem: | awk '{print $2}') : $(nproc)))
+          echo "number_of_jobs=$VALUE" >> $GITHUB_OUTPUT
+
+  clean-build-and-test-linux:
+    # Ensures that the build works from a clean build directory.
+    name: "Clean build and tests"
+    needs: [ get-resources ]
     container:
-      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}
+      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}-${{matrix.sanitizer}}
+      env:
+        MOLD_JOBS: 1
+      options: --user root
+    timeout-minutes: 40
+    runs-on: [ self-hosted, linux, Build, "${{matrix.arch}}" ]
+    strategy:
+      fail-fast: false
+      matrix:
+        arch: [ x64 ]
+        stdlib: [ 'libcxx' ]
+        build_type: [ 'Debug' ]
+        sanitizer: [ 'none' ]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ inputs.ref }}
+      - name: Configure NebulaStream
+        run: |
+          rm -rf build || true
+          cmake -GNinja -B build -DUSE_SANITIZER=${{ matrix.sanitizer }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DNES_LOG_LEVEL=DEBUG
+      - name: Build NebulaStream
+        shell: bash
+        run: |
+          source .github/.env/test-${{matrix.sanitizer}}.env
+          cmake --build build -j ${{needs.get-resources.outputs.number_of_jobs}} -- -k 0
+      - name: Run Tests
+        run: ctest --test-dir build -j ${{needs.get-resources.outputs.number_of_jobs}} --output-on-failure --output-junit /junit.xml --timeout 600
+      - uses: actions/upload-artifact@v4
+        # Upload all log and stat files if any of the tests has failed.
+        name: Upload Test Logs on Failure
+        if: ${{ failure() && !github.event.act }}
+        with:
+          name: logs-${{ matrix.arch }}-${{ matrix.stdlib }}-${{ matrix.build_type }}
+          path: |
+            build/**/*.log
+            build/**/*.stats
+
+  build-and-test-linux:
+    name: "Build and tests: ${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.build_type}}-${{ matrix.sanitizer }}"
+    needs: [ get-resources ]
+    container:
+      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}-${{matrix.sanitizer}}
       volumes:
         - ccache:/ccache
+        - test-file-cache:/test-file-cache
       env:
         CCACHE_DIR: /ccache
         MOLD_JOBS: 1
@@ -32,22 +91,52 @@ jobs:
         arch: [ x64, arm64 ]
         stdlib: [ 'libstdcxx', 'libcxx' ]
         build_type: [ 'Debug', 'RelWithDebInfo' ]
+        sanitizer: [ 'address', 'undefined', 'thread', 'none' ]
+        exclude:
+          # Due to limited capacity, we disable sanitizer and libstdc++ tests on arm machines
+          - arch: arm64
+            stdlib: 'libstdcxx'
+          - arch: arm64
+            sanitizer: 'address'
+          - arch: arm64
+            sanitizer: 'undefined'
+          - arch: arm64
+            sanitizer: 'thread'
+          # TODO #808 Enable TSAN with libc++
+          - stdlib: 'libcxx'
+            sanitizer: 'thread'
     steps:
       - uses: actions/checkout@v4
         with:
           ref: ${{ inputs.ref }}
       - name: Configure NebulaStream
-        run: cmake -GNinja -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DNES_LOG_LEVEL=DEBUG
+        run: |
+          cmake -GNinja -B build -DExternalData_OBJECT_STORES=/test-file-cache -DUSE_SANITIZER=${{ matrix.sanitizer }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DNES_LOG_LEVEL=DEBUG
       - name: Build NebulaStream
-        run: cmake --build build -j -- -k 0
+        shell: bash
+        run: |
+          source .github/.env/test-${{matrix.sanitizer}}.env
+          cmake --build build -j ${{needs.get-resources.outputs.number_of_jobs}}  -- -k 0
       - name: Run Tests
         # timeout of 600 seconds due to systest. Increase this number only if we encounter timeouts in our systests.
-        run: ctest --test-dir build -j --output-on-failure --output-junit /junit.xml --timeout 600
+        shell: bash
+        run: |
+          source .github/.env/test-${{matrix.sanitizer}}.env
+          ctest --test-dir build -j ${{needs.get-resources.outputs.number_of_jobs}} --output-on-failure --output-junit /junit.xml --timeout 600 ${ADDTIONAL_CTEST_ARGS}
+      - name: Upload Test Logs on Failure
+        uses: actions/upload-artifact@v4
+        # Upload all log and stats files if any of the tests has failed.
+        if: ${{ failure() && !github.event.act }}
+        with:
+          name: logs-${{ matrix.arch }}-${{ matrix.stdlib }}-${{ matrix.build_type }}
+          path: |
+            build/**/*.log
+            build/**/*.stats
       - name: Upload Test Summary
         uses: actions/upload-artifact@v4
         if: ${{ !cancelled() && !github.event.act }}
         with:
-          name: junit-${{ matrix.arch }}-${{ matrix.stdlib }}-${{ matrix.build_type }}.xml
+          name: junit-${{ matrix.arch }}-${{ matrix.stdlib }}-${{ matrix.sanitizer }}-${{ matrix.build_type }}.xml
           path: /junit.xml
 
   # We want to test if our cmake log level flag works correctly. Therefore, we need to build and run the tests with different log levels.
@@ -55,7 +144,7 @@ jobs:
   build-and-test-log-level:
     name: "Build and test log level: ${{matrix.arch}}-${{matrix.stdlib}}-${{matrix.build_type}}-log-level"
     container:
-      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}
+      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}-none
       volumes:
         - ccache:/ccache
       env:
@@ -79,7 +168,7 @@ jobs:
           ref: ${{ inputs.ref }}
       - name: Build and Run Log Level Tests
         run: |
-          for LOG_LEVEL in TRACE DEBUG INFO WARN ERROR; do
+          for LOG_LEVEL in TRACE DEBUG INFO WARN ERROR FATAL_ERROR LEVEL_NONE; do
             echo "Running tests with log level: $LOG_LEVEL"
             cmake -GNinja -B build -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DNES_LOG_LEVEL=$LOG_LEVEL
             cmake --build build --target nes-common-tests -j -- -k 0
@@ -96,7 +185,7 @@ jobs:
   build-without-tests:
     name: "Build with disabled tests: ${{matrix.arch}}-${{matrix.stdlib}}"
     container:
-      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}
+      image: nebulastream/nes-development:${{ inputs.dev_image_tag }}-${{ matrix.stdlib }}-none
       volumes:
         - ccache:/ccache
       env:
